apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: gateway
          image: user03.azurecr.io/gateway:latest
          ports:
            - containerPort: 8080
